// This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://example.com';
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'public-key-placeholder';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// MOCK SUPABASE CLIENT for GitHub Pages Demo
// Removes all real database dependencies
export const supabase = {
  from: (table: string) => ({
    select: () => Promise.resolve({ data: [], error: null }),
    upsert: () => Promise.resolve({ error: null }),
    delete: () => Promise.resolve({ error: null }),
    eq: () => ({
      eq: () => Promise.resolve({ error: null }),
      delete: () => Promise.resolve({ error: null }),
      select: () => Promise.resolve({ data: [], error: null }),
    }),
    url: {
      searchParams: new URLSearchParams()
    }
  }),
  storage: {
    from: (bucket: string) => ({
      upload: () => Promise.resolve({ error: null }),
      getPublicUrl: (path: string) => ({ data: { publicUrl: '' } }),
      remove: () => Promise.resolve({ error: null }),
    }),
  },
  auth: {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    signInWithOtp: () => Promise.resolve({ error: null }),
    verifyOtp: () => Promise.resolve({ data: { session: null }, error: null }),
    signOut: () => Promise.resolve({ error: null }),
  }
} as any;
